version: '3'

volumes:
  pg-data:

services:
  postgres:
    image: postgres:9.6.3
    volumes:
      - pg-data:/var/lib/postgresql/data

  bob:
    depends_on:
      - postgres
    environment:
      GITHUB_CLIENT_ID:
      GITHUB_CLIENT_SECRET:
      ROOT_USER_ID:
      WATCH: 1
    image: coderiety/bob:graphql
    ports:
      - 80:80
    volumes:
      - ./.eslintrc:/code/.eslintrc
      - ./.stylelintrc:/code/.stylelintrc
      - ./bin:/code/bin
      - ./etc:/code/etc
      - ./package.json:/code/package.json
      - ./src:/code/src
      - /var/run/docker.sock:/var/run/docker.sock
