version: '3.5'

x-bob-shared: &x-bob-shared
  build: .
  environment:
    GITHUB_CLIENT_ID:
    GITHUB_CLIENT_SECRET:
    MAIL_ENABLED:
    MAIL_FROM_ADDRESS:
    MAIL_FROM_NAME:
    MAIL_SMTP_URL:
    ROOT_EMAIL_ADDRESS:
    WATCH: 1
  volumes:
    - ./.eslintrc:/code/.eslintrc
    - ./.stylelintrc:/code/.stylelintrc
    - ./bin:/code/bin
    - ./etc:/code/etc
    - ./package.json:/code/package.json
    - ./src:/code/src
    - /var/run/docker.sock:/var/run/docker.sock

services:
  postgres:
    image: postgres:10.2-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data

  bob:
    <<: *x-bob-shared
    depends_on:
      - bob-inotify-fix
      - postgres
    ports:
      - 80:80

  # HACK: Until https://github.com/docker/for-mac/issues/681 is fixed
  bob-inotify-fix:
    <<: *x-bob-shared
    command: ["tail", "-f", "/dev/null"]
    stop_signal: SIGKILL

volumes:
  pg-data:
